% export_csv_files_syllables
function export_csv_files_syllables(handles)

    csvdir=fullfile(handles.audiodir,'CSV');
    if ~exist(csvdir,'dir')
      mkdir(csvdir)
    end

    % csv header
    csv_header=sprintf('%s,%s (sec),%s (sec),%s (sec),%s (msec),%s (kHz),%s (kHz),%s (kHz),%s (kHz),%s (kHz),%s (kHz),%s (dB),%s (dB)\n', ...
        'Syllable number', ...
        'Syllable start time', ...
        'Syllable end time', ...
        'inter-syllable interval', ...
        'syllable duration', ...
        'starting frequency', ...
        'final frequency', ...
        'minimum frequency', ...
        'maximum frequency', ...
        'mean frequency', ...
        'frequency bandwidth', ...
        'total syllable energy', ...
        'peak syllable amplitude');

    csvfile=strrep(fullfile(csvdir, strrep(handles.filename,'wav','csv')),'WAV','csv');
    fid = fopen(csvfile,'wt');
    fwrite(fid, csv_header);

    for syllable_ndx = 1:size(handles.syllable_stats,2)

        if handles.syllable_stats{14,syllable_ndx} == -100
            inter_syllable_interval='_';
        else
            inter_syllable_interval=sprintf('%.5f',handles.syllable_stats{14,syllable_ndx}/1000);
        end

        % print syllable information
        syllable_info=sprintf('%i,%.4f,%.4f,%s,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f\n', ...
            syllable_ndx, ...
            handles.syllable_stats{8,syllable_ndx}, ...
            handles.syllable_stats{9,syllable_ndx}, ...
            inter_syllable_interval, ...
            handles.syllable_stats{13,syllable_ndx}, ...
            handles.syllable_stats{2,syllable_ndx}, ...
            handles.syllable_stats{3,syllable_ndx}, ...
            handles.syllable_stats{4,syllable_ndx}, ...
            handles.syllable_stats{5,syllable_ndx}, ...
            handles.syllable_stats{10,syllable_ndx}, ...
            handles.syllable_stats{6,syllable_ndx}, ...
            handles.syllable_stats{11,syllable_ndx}, ...
            handles.syllable_stats{12,syllable_ndx});
            fwrite(fid, syllable_info);
    end

    fclose(fid);

end